### ISSUE TITLE
Specific boost version too restrictive

### ISSUE THREAD

**Issue by marip8** [tesseract-robotics-packaging/tesseract-robotics-planning-feedstock#1]
I'm trying to create an environment with `tesseract_planning` and a few other packages, and I'm having difficulties with dependency resolution due to the specific version of `boost` required by `tesseract-planning`, `descartes`, and `ompl` (1.74.0).

```
tesseract-robotics-motion-planners 0.9.3 ha7e12ad_3
---------------------------------------------------
file name   : tesseract-robotics-motion-planners-0.9.3-ha7e12ad_3.tar.bz2
name        : tesseract-robotics-motion-planners
version     : 0.9.3
build       : ha7e12ad_3
build number: 3
size        : 706 KB
license     : Apache-2.0 AND BSD-3-Clause AND BSD-2-Clause
subdir      : linux-64
url         : https://conda.anaconda.org/tesseract-robotics/linux-64/tesseract-robotics-motion-planners-0.9.3-ha7e12ad_3.tar.bz2
md5         : ea461895d904f96e9897debaba4e9d2a
timestamp   : 2022-03-24 02:59:20 UTC
dependencies: 
  - boost-cpp >=1.74.0,<1.74.1.0a0
  - console_bridge >=1.0.2,<1.1.0a0
  - descartes-light
  - eigen
  - libgcc-ng >=10.3.0
  - libstdcxx-ng >=10.3.0
  - ompl >=1.5.2,<1.6.0a0
  - tesseract-robotics-command-language
  - tesseract-robotics-common
  - tesseract-robotics-environment
  - trajopt
  - trajopt-ifopt
  - trajopt-sco
  - trajopt-sqp
```

I don't think there is anything specific about this particular release of `boost` (seeing as we also build these repos with 1.65.0 on Ubuntu 18.04) that makes it explicitly required. Is there are reason that is specified [here](https://github.com/tesseract-robotics-packaging/tesseract-robotics-planning-feedstock/blob/1d567a1b253ce956ab59554f75053b2a679ab2f3/.ci_support/linux_64_.yaml#L1-L2) and [here](https://github.com/tesseract-robotics-packaging/tesseract-robotics-planning-feedstock/blob/1d567a1b253ce956ab59554f75053b2a679ab2f3/.ci_support/win_64_.yaml#L1-L2)? If not, is there a way to remove it or at least expand it to more versions of `boost` (e.g. >= 1.65.0)

**Comment by johnwason** [comment]
@marip8 

You need to use conda-smithy for these feedstocks. The only files you actually write yourself are:

* the contents of recipe/
* conda-forge.yml

All of the other files are generated by running:

conda smithy rerender

in the root folder of the repo.

https://github.com/conda-forge/conda-smithy

**Comment by johnwason** [comment]
If you want to use conda build, you can do

    conda build -m .ci_support/linux_64_.yaml

replacing with the configuration you want to build. On linux, you can use the `build-locally.py` script and it will use a docker.

**Comment by johnwason** [comment]
@marip8 sorry I read your question wrong... I haven't updated these packages for a long time, so they are probably using the wrong versions of dependency packages. I was having trouble with them segfaulting so I haven't done much recently. I can give it another try and let you know when they are up.

**Comment by marip8** [comment]
Sounds good; I'm happy to help try this as well, but this is my first foray into conda. Do you test these files and configurations by building locally with the script you linked or some other way?

**Comment by johnwason** [comment]
I build locally to test, and then use the GitHub Actions. I haven't been running the tests on each package, but I have been having so many errors I will have to start doing so.
